services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    ports:
      - 8096:8096/tcp
      - 7359:7359/udp
    volumes:
      - type: bind
        source: /home/jellyfin/cache
        target: /cache
      - type: bind
        source: /home/jellyfin/config
        target: /config
      - type: bind
        source: /home/jellyfin/media
        target: /media
        read_only: true
    restart: 'unless-stopped'
    # Optional - alternative address used for autodiscovery
    extra_hosts:
      - 'host.docker.internal:host-gateway'
